### PR TITLE
Added questions on data encapsulation 

### PR DESCRIPTION
**Pull request by yashrajb**

### CODE REVIEW

**Comment by sudheerj** [comment]
Data encapsulation is not specific to javascript. The question should answer "What is data encapsulation in javascript". Also, the function names should be improved in another question too. Please update PR..

**Comment by yashrajb** [comment]
@sudheerj I made the necessary changes. please review it

**Comment by yashrajb** [comment]
@sudheerj I made the necessary changes. please review it

**Comment by codewithviju** [comment]
[](url)

**Comment by sudheerj** [comment]
@yashrajb There are still conflicts in PR. Please check

**Comment by sudheerj** [comment]
@yashrajb Please resolve the conflicts

**Comment by yashrajb** [comment]
@sudheerj conflicts resolved

**Comment by sudheerj** [comment]
@yashrajb  I adde these changes manually considering conflicts. Thanks

**Pull request closed without merging**
