### PR TITLE
question 390 added

### PR DESCRIPTION
**Pull request by riyaz2014**
i have added the answer of question 390 and made the required changes

### CODE REVIEW

**Comment by sudheerj** [comment]
The statements are still not perfect in terms off grammar

**Comment by riyaz2014** [comment]
ok I am correcting it

**Comment by riyaz2014** [comment]
I have modified the answer and added images for better explanation can you please review it

**Comment by sudheerj** [comment]
It has to be improved further. I will merge and update the statements

**Comment by riyaz2014** [comment]
ok

**Comment by riggulate** [comment]
Hey can you send me that also pls

**Review by Bharath58120 — APPROVED** [review]

**Comment by sudheerj** [comment]
Hello @riyaz2014, Thanks for PR. Can you please create all the changes in a single commit? It is difficult to understand the exact changes right now.

**Pull request closed without merging**
