### PR TITLE
Added Question about Revocable Proxy with example code

### PR DESCRIPTION
**Pull request by darkhorse-91**
Hey,

Please check this PR -

### CODE REVIEW

**Comment by sudheerj** [comment]
@darkhorse-91  Thanks for PR. The answer needs to be explained in detail and the grammatically need to improved. Can you update that?

**Comment by darkhorse-91** [comment]
> @darkhorse-91 Thanks for PR. The answer needs to be explained in detail and the grammatically need to improved. Can you update that?

Hi @sudheerj 
Added more explanation and fixed the grammer.
Please review -

**Comment by darkhorse-91** [comment]
Hey @sudheerj ,
Please review now

**Comment by sudheerj** [comment]
Hello @darkhorse-91, The PR has conflicts. Can you please create a new PR with in a single commit for this question?

**Pull request closed without merging**
