### PR TITLE
ways to create a function

### PR DESCRIPTION
**Pull request by iamangelmp**
description and examples to use the forms to create and usage a function 👊🏻

### CODE REVIEW

**Comment by sudheerj** [comment]
@iamangelmp  Can you resolve the conflicts

**Comment by iamangelmp** [comment]
Done !

**Review by iamangelmp — COMMENTED** [review]
Code formatted with prettier, content is the same

**Comment by sudheerj** [comment]
I'm not able to your changes clearly in the commit(It shows many many differences). Can you create a separate PR

**Pull request closed without merging**
