### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by SachinBahukhandi**
Fixed the Object's assign method: https://github.com/sudheerj/javascript-interview-questions?tab=readme-ov-file#what-are-the-possible-ways-to-create-objects-in-javascript

### CODE REVIEW

**Review by amitkumar-niranjan — COMMENTED** [review]
Please don't make unnecessary commits

**Comment by sudheerj** [comment]
The mentioned naming changes are not required. So I'm closing this pull request.

**Comment by SachinBahukhandi** [comment]
So this change was made because the statement:
```
  const staff = Object.assign({}, orgObject, carObject);
```
Would be causing an error because the variables have been defined as:

```
const orgObj = { company: 'XYZ Corp'};
const carObj = { name: 'Toyota'};
```

**Comment by sudheerj** [comment]
@SachinBahukhandi  Got it now. Thanks for the PR

**Pull request merged**
