### PR TITLE
Update accidental-global.js

### PR DESCRIPTION
**Pull request by codernkb**

### CODE REVIEW

**Comment by sudheerj** [comment]
@codernkb Can you describe the changes and what it fixes?

**Comment by codernkb** [comment]
> @codernkb Can you describe the changes and what it fixes?

**Comment by codernkb** [comment]
I have changed/deleted the 'let' word since it has block scope and was preventing 'x' from taking the value from 'y' (which has a global scope as in JS a variable can also be declared without using any of 'var', 'let' or 'const'. Now in the output typeof 'x' is also a number.

p.s- just joined github and was practicing your questions. they are really helpful. 
Was that code there not be fixed? or it is written that way to practice...

**Comment by sudheerj** [comment]
The code is intentional to test the global and block scope behavior in this scenario.

**Pull request closed without merging**
